name: DXBiometric
options:
  bundleIdPrefix: com.definex
  deploymentTarget:
    iOS: "12.0"
  
settings:
  base:
    SWIFT_VERSION: "5.7"
    BUILD_LIBRARY_FOR_DISTRIBUTION: YES
    SKIP_INSTALL: NO
    IPHONEOS_DEPLOYMENT_TARGET: "12.0"

targets:
  DXBiometric:
    type: framework
    platform: iOS
    sources:
      - path: Sources/DXBiometric
        excludes:
          - "Resources/**"
    settings:
      base:
        PRODUCT_NAME: DXBiometric
        PRODUCT_BUNDLE_IDENTIFIER: com.definex.DXBiometric
        DEFINES_MODULE: YES
        INFOPLIST_FILE: Sources/DXBiometric/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
    scheme:
      testTargets: []
      gatherCoverageData: false

schemes:
  DXBiometric:
    build:
      targets:
        DXBiometric: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

